@url = http://localhost:5000/conferences-module

@hostId = 53b77421-a239-4997-919a-b879b12f7517

@conferenceId = 4a0b5d94-e5b0-4274-afe1-4397bbcbfff8

GET {{url}}

###
POST {{url}}/hosts
Content-Type: application/json

{
    "name": "Host #1",
    "description": "Lorem ipsum"
}
###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{
    "name": "Host #2",
    "description": "Lorem ipsum"
}

###
DELETE  {{url}}/hosts/{{hostId}}


###
POST {{url}}/conferences
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "Conference #1",
    "description": "Lorem ipsum",
    "location": "Test 123",
    "from": "2021-05-01",
    "to": "2021-05-02",
    "participantsLimit": 100,
    "logoUrl": null
}
###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
    "name": "Conference #2",
    "description": "Lorem ipsum",
    "location": "Test 12121212"
}

###
DELETE  {{url}}/conferences/{{conferenceId}}